name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: |
          echo "Hello World!"
          echo "What's the Hostname of the server ?"
          hostname -f
          echo "What's the present working directory ?"
          pwd
          echo "What's the version of Java on the server ?"
          java -version
