name: first-action-script
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Run a multi-line script
        run: |
          echo "Where I am right now"
          pwd
          echo "Listing the contents..."
          ls -lrt
          echo "Executing Script..."
          ./scripts/myFirstActionScript.sh
